import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ToasterProvider } from "@/components/toaster";
import { ErrorSuppressor } from "@/components/error-suppressor";
import "@/styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              // Early suppression of network errors (runs before React)
              (function() {
                if (typeof window === 'undefined') return;
                
                const originalError = console.error;
                const originalWarn = console.warn;
                
                console.error = function(...args) {
                  const message = String(args.join(' '));
                  if (
                    message.includes('Failed to fetch') ||
                    message.includes('NetworkError') ||
                    message.includes('Network request failed') ||
                    message.includes('AuthRetryableFetchError') ||
                    (message.includes('TypeError') && message.includes('fetch')) ||
                    message.includes('fetch failed')
                  ) {
                    return;
                  }
                  originalError.apply(console, args);
                };
                
                console.warn = function(...args) {
                  const message = String(args.join(' '));
                  if (
                    message.includes('AuthRetryableFetchError') ||
                    message.includes('Failed to fetch') ||
                    message.includes('NetworkError') ||
                    (message.includes('fetch') && message.includes('retry'))
                  ) {
                    return;
                  }
                  originalWarn.apply(console, args);
                };
                
                // Suppress unhandled promise rejections
                window.addEventListener('unhandledrejection', function(event) {
                  const message = String(event.reason?.message || event.reason || '');
                  if (
                    message.includes('Failed to fetch') ||
                    message.includes('NetworkError') ||
                    message.includes('AuthRetryableFetchError') ||
                    (message.includes('TypeError') && message.includes('fetch'))
                  ) {
                    event.preventDefault();
                  }
                });
              })();
            `,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <ErrorSuppressor />
        {children}
        <ToasterProvider />
      </body>
    </html>
  );
}
